macro(detect_system OS_VAR)
  if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(${OS_VAR} "OSX")
  elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(${OS_VAR} "Linux")
  endif()
endmacro()

# Usage: cmake -DBUILD_SHARED_LIBS=ON/OFF .
function(setup_option_shared_lib)
  option(BUILD_SHARED_LIBS "Build Shared Libraries" OFF)
  if(BUILD_SHARED_LIBS)
    message(STATUS "Enabled Shared Library Building")
    if(UNIX AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
      add_definitions("-fPIC")
    endif()
  endif()
endfunction()

function(simple_find_library var name1 libpath)
  find_library(${var} ${name1} HINTS ${libpath})
  if(${${var}} MATCHES "NOTFOUND")
    message(FATAL_ERROR "Unable to find library: ${${var}}")
  else()
    message(STATUS "Found library ${${var}}")
  endif()
endfunction()
