# At the moment, we assume Clang with libc++ is used to build WzToNx
function(enable_cxx11)
  if("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    message(STATUS "${PROJECT_NAME}: Enabling Clang C++11 support")
    message(STATUS "${PROJECT_NAME}: Make sure libc++ is installed")
    ADD_COMPILE_OPTIONS(-std=c++11 -stdlib=libc++)
  else()
    message(FATAL_ERROR "Only Clang and msvc are supported")
  endif()
endfunction()

# Usage: cmake -DBUILD_SHARED_LIBS=ON/OFF .
function(setup_option_shared_lib)
  set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build Shared Libraries")
  if(BUILD_SHARED_LIBS)
    message(STATUS "Enabled Shared Library Building")
    if(UNIX AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64")
      add_definitions("-fPIC")
    endif()
  endif()
endfunction()

function(simple_find_library var name1 libpath)
  find_library(${var} ${name1} HINTS ${libpath})
  if(${${var}} MATCHES "NOTFOUND")
    message(FATAL_ERROR "Unable to find library: ${${var}}")
  else()
    message(STATUS "Found library ${${var}}")
  endif()
endfunction()
